version: "3.5"

services:
  api01: &api
    build: .
    # image: norbajr/rinha-norba-renan-elixir:latest
    network_mode: host
    environment:
      - RELEASE_NODE=rinha1
      - RELEASE_COOKIE=rinha
      - PORT=4000

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "260MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    network_mode: host
    environment:
      - RELEASE_NODE=rinha2
      - RELEASE_COOKIE=rinha
      - PORT=4001

    depends_on:
      - api01

    command: [ "sh", "-c", "sleep 3 && /app/bin/rinha start" ]

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "20MB"
