version: "3.5"

services:
  api01: &api
    build: .
    # image: rinha-norba-renan-elixir:latest
    hostname: api01
    environment:
      - RELEASE_NODE=rinha
      - RELEASE_COOKIE=rinha

    deploy:
      resources:
        limits:
          cpus: "1.2"
          memory: "530MB"

    networks:
      - rinha-nginx-2024q1

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    environment:
      - RELEASE_NODE=rinha
      - RELEASE_COOKIE=rinha

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "20MB"

    networks:
      - rinha-nginx-2024q1

# O uso do modo `bridge` deve ser adequado à carga que será usada no teste.
# A edição anterior se beneficiou do modo host pois o volume de requisições
# era relativamente alto e a virtualização da rede se tornou um gargalo, mas
# este modo é mais complexo de ser configurado. Fique à vontade para usar o
# modo que quiser desde que não conflite com portas trivialmente usadas em um
# SO.
networks:
  rinha-nginx-2024q1:
    driver: bridge
