version: "3.5"

services:
  api01: &api
    build: .
    # image: norbajr/rinha-norba-renan-elixir:latest
    hostname: api01
    container_name: api01
    # network_mode: host
    networks:
      - elixir-cluster
    environment:
      - RELEASE_NODE=rinha
      - RELEASE_COOKIE=rinha
      # - PORT=4001

    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "260MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    container_name: api02

    depends_on:
      - api01
    # command: [ "sh", "-c", "sleep 3 && /app/bin/rinha start" ]

  nginx:
    image: nginx:latest
    container_name: nginx
    # network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - elixir-cluster
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

networks:
  elixir-cluster:
    driver: bridge
